version = 0.1

[default.global.parameters]
stack_name = "burger-api"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
docker_host = "unix:///Users/sarahcrowder/.docker/run/docker.sock"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
s3_prefix = "burger-api"
disable_rollback = false
image_repositories = []
